# Generated by Django 4.1.3 on 2022-12-02 14:20

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sending', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeMobile',
            fields=[
                ('codemobile_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_mobile', models.IntegerField(default=1, unique=True, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag', models.TextField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='tags',
        ),
        migrations.AlterField(
            model_name='mailing',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 2, 17, 20, 50, 374405)),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 2, 17, 20, 50, 374389)),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_send',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 2, 17, 20, 50, 374786)),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='mailing',
            name='code_mailing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='code_mailing', to='sending.codemobile', to_field='code_mobile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailing',
            name='tag_mailing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tag_mailing', to='sending.tag', to_field='tag'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='code_mobile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_code_mobile', to='sending.codemobile', to_field='code_mobile'),
        ),
        migrations.AlterField(
            model_name='client',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_tag', to='sending.tag', to_field='tag'),
        ),
    ]
