# Generated by Django 4.1.3 on 2022-12-03 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sending', '0002_codemobile_tag_remove_mailing_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 3, 16, 13, 32, 140519)),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 3, 16, 13, 32, 140502)),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_send',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 3, 16, 13, 32, 140872)),
        ),
    ]
